### ISSUE TITLE
Why create the temporary std::string's?

### ISSUE THREAD

**Issue by niXman** [amallia/better_assert#1]
Hi,

There is no need to create the two temporary `file` and `condition` objects that, moreover, allocates memory in the heap: https://github.com/amallia/better_assert/blob/c5e3033a9b17e27401094e13ee93037f94f9d639/include/better_assert/better_assert.hpp#L19

**Comment by amallia** [comment]
I believe this is needed. If you use `__FILE__` and `__LINE__` directly in the function it will print `better_assert.hpp` as fine and the line of the `cerr` call. Try it yourself if you dont believe it :)

Anyway it is passed as reference and it is referring to a compiler defined value which is probably const static. So it should not allocate anything :)

**Comment by niXman** [comment]
I think this also applies to the `message` object.

**Comment by amallia** [comment]
Can you provide an example?

**Comment by niXman** [comment]
> Anyway it is passed as reference and it is referring to a compiler defined value which is probably const static. So it should not allocate anything :)


You're wrong.
The two temporary objects will be created here that allocate memory on the heap and copy the `static const char [N]` arrays.

**Comment by amallia** [comment]
Okay, that is true. Can you provide an example to avoid it?

**Comment by niXman** [comment]
https://wandbox.org/permlink/t9aCUbPmfZ8FWqNK

**Comment by amallia** [comment]
Yes, I should have said in C++style :)

**Comment by amallia** [comment]
I can change it for `file` and `condition`, will not change it for `message` as it might be the case that someone passes an actual string.

**Comment by niXman** [comment]
Moreover, the `file` and `line` you can be put in one `static const char[]` array: https://wandbox.org/permlink/OfHVWipSg1sSKMgV

**Comment by niXman** [comment]
> I can change it for file and condition, will not change it for message as it might be the case that someone passes an actual string.

Or maybe the user of your code will always be hardcoding messages? ;)
But your code in this case will always create a temporary object ;)

**Comment by niXman** [comment]
In C++ it is considered a bad form to "pay" for what you do not use. I mean the creation of a temporary object and the memory allocation in the heap.

**Comment by amallia** [comment]
> In C++ it is considered a bad form to "pay" for what you do not use. I mean the creation of a temporary object and the memory allocation in the heap.
You might want to reuse the same message among multiple asserts. So it makes sense to allocate a single string and pass it around.

I can have two overloads...

> https://wandbox.org/permlink/OfHVWipSg1sSKMgV

I like this one, a single `#define _STRINGIZE(x) #x` should be enough...
EDIT: no is not

**Comment by amallia** [comment]
Added your suggestions. Thanks a lot!
Also I have done the overload for char*/string&.

Appreciated your help!

**Comment by niXman** [comment]
But, what's this?: `std::cerr << "oooooooo" << std::endl;` ;)
In line 33.

**Comment by amallia** [comment]
Oh sh*t :)
